spring:
  servlet:
    multipart:
      max-file-size: 50MB        # individual file size limit
      max-request-size: 100MB    # total request size limit
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
    url: jdbc:postgresql://localhost:5432/application
    username: agripro
    password: agripro
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.type.mapping: >
          applicationSubmittedEvent:com.hashjosh.kafkacommon.application.ApplicationSubmittedEvent

    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
        spring.json.type.mapping: >
          applicationSubmittedEvent:com.hashjosh.kafkacommon.application.ApplicationSubmittedEvent

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

token:
  secret: lJ43fZtwCfh2qNM0uFx3mHSYGh/qrfXUtrM4Vl/kiZE=
  accessTokenExpirationMs: 14400000                # 4 hours
  accessTokenExpirationRememberMeMs: 2592000000    # 30 days
  refreshTokenExpirationMs: 86400000               # 1 day
  refreshTokenExpirationRememberMeMs: 345600000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
trusted:
  internal-service-ids:
    - agriculture-service
    - application-service
    - verification-service
    - realtime-service
    - insurance-service
    - notification-service
    - communication-service
    - farmer-service
    - application-service
    - pcic-service
    - document-service
    - rsbsa-service
    - program-service

server:
  port: 8010



